# Generated by Django 4.0.4 on 2022-04-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='owner',
        ),
    ]
