# Generated by Django 4.0.4 on 2022-04-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tattoo',
            name='review',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='tattoos.artist'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tattoos', to='tattoos.category'),
        ),
    ]
