# Generated by Django 4.0.4 on 2022-04-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoo',
            name='categories',
        ),
        migrations.AddField(
            model_name='tattoo',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='tattoos.category'),
            preserve_default=False,
        ),
    ]
