# Generated by Django 4.0.4 on 2022-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0002_artist_category_tattoo_review_tattoo_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoo',
            name='review',
        ),
    ]
